name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
      - name: Checkout
        uses: actions/checkout@master
      - name: Download dependencies
        run: go mod download
      - name: Run test
        run: go test -test.v -coverprofile=coverage.out -covermode=count
      - name: Publish coverage
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
